/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishRouteImport } from './routes/wish'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'

const WishRoute = WishRouteImport.update({
  id: '/wish',
  path: '/wish',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/wish': typeof WishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/wish': typeof WishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/letter': typeof LetterRoute
  '/memories': typeof MemoriesRoute
  '/wish': typeof WishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gallery' | '/letter' | '/memories' | '/wish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gallery' | '/letter' | '/memories' | '/wish'
  id: '__root__' | '/' | '/gallery' | '/letter' | '/memories' | '/wish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  LetterRoute: typeof LetterRoute
  MemoriesRoute: typeof MemoriesRoute
  WishRoute: typeof WishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wish': {
      id: '/wish'
      path: '/wish'
      fullPath: '/wish'
      preLoaderRoute: typeof WishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  LetterRoute: LetterRoute,
  MemoriesRoute: MemoriesRoute,
  WishRoute: WishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
